app:
  name: 'service-url-shortener'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'

postgres:
  pool_max: 2

grpc:
  network: 'tcp'
  port: '50051'

digitiser:
  # sensitive values, changes can lead to maximum allowable integer errors
  # in code or storage, check digitiser.Max()
  base: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_'
  length: 5

url:
  blank: 'http://127.0.0.1'