app:
  name: 'service-url-shortener'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'

postgres:
  pool_max: 2

redis:
  db: 0

grpc:
  network: 'tcp'
  port: '50051'

# sensitive values
# changes can lead to maximum allowable integer errors
# in code or storage, check digitiser.Max()
digitiser:
  max_repo_int: 2147483647 # postgres_max_int
  base: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_'
  length: 5

url:
  blank: 'http://127.0.0.1:8080/'