app:
  name: 'service-url-shortener'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'

postgres:
  pool_max: 2

digitiser:
  base: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_'
  length: 5

url:
  blank: 'http://localhost'